spring:
  application:
    name: Spring Boot Caching With Redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/redis?createDatabaseIfNotExist=true&useSSL=false
    name:
    username: root
    password: mynewpassword
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
#    database: MYSQL
#    show_sql: true
#    properties:
#      hibernate.cache.use_second_level_cache: false
#      hibernate.cache.use_query_cache: false
#      hibernate.generate_statistics: true
  redis:
    host: localhost
    port: 6379